apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: nuclio-function-deployer
  namespace: nuclio
rules:
- apiGroups: [""]
  resources: ["services", "configmaps", "pods", "pods/log", "events"]
  verbs: ["*"]
- apiGroups: ["apps", "extensions"]
  resources: ["deployments"]
  verbs: ["*"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["*"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["*"]
- apiGroups: ["metrics.k8s.io", "custom.metrics.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["*"]
---
# Bind the "nuclio" service account (used by controller / dashboard) to the nuclio-function-deployer role,
# allowing them to create deployments, services, etc
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: nuclio-function-deployer-rolebinding
  namespace: nuclio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nuclio-function-deployer
subjects:
- kind: ServiceAccount
  name: nuclio
  namespace: nuclio
---
# All access to the function/project/functionevents custom resource definition
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: nuclio-functioncr-admin
rules:
- apiGroups: ["nuclio.io"]
  resources: ["nucliofunctions", "nuclioprojects", "nucliofunctionevents", "nuclioapigateways"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]

---

# Bind the "nuclio" service account (used by controller / dashboard) to the nuclio-functioncr-admin role,
# allowing them to create / delete function custom resource definitions in the "nuclio" namespace
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: nuclio-functioncr-admin-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nuclio-functioncr-admin
subjects:
- kind: ServiceAccount
  name: nuclio
  namespace: nuclio
